[package]
name = "raytracer-rust"
version = "0.1.0"
authors = ["vincent@etter.io"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.15.0"
impl_ops = "0.1.1"
rand = "0.8.3"